import XCTest
@testable import SideTerminalCore

final class TerminalConfigTests: XCTestCase {
    private func input(
        opacity: Double = 0.82,
        blur: Double = 24,
        cursor: String = "block",
        fontSize: Double = 13,
        fontFamily: String = "",
        theme: TerminalThemeMode = .system,
        workingDirectory: String = "",
        home: String = "/Users/test",
        shell: String = ""
    ) -> TerminalConfigInput {
        TerminalConfigInput(
            backgroundOpacity: opacity,
            blurAmount: blur,
            cursorStyle: cursor,
            fontSize: fontSize,
            fontFamily: fontFamily,
            theme: theme,
            workingDirectory: workingDirectory,
            homeDirectory: home,
            shellPath: shell
        )
    }

    private func lines(_ input: TerminalConfigInput) -> [String] {
        renderTerminalConfig(input).split(separator: "\n").map(String.init)
    }

    func testHasHeaderAndTrailingNewline() {
        let out = renderTerminalConfig(input())
        XCTAssertTrue(out.hasPrefix("# Generated by SideTerminal"))
        XCTAssertTrue(out.hasSuffix("\n"))
    }

    func testAlwaysDisablesShellCursorOverride() {
        XCTAssertTrue(lines(input()).contains("shell-integration-features = no-cursor"))
    }

    func testSystemThemeEmitsConditionalTheme() {
        let l = lines(input(theme: .system))
        XCTAssertTrue(l.contains("theme = light:Apple System Colors Light,dark:Apple System Colors"))
        XCTAssertTrue(l.contains("window-theme = auto"))
    }

    func testLightTheme() {
        let l = lines(input(theme: .light))
        XCTAssertTrue(l.contains("theme = Apple System Colors Light"))
        XCTAssertTrue(l.contains("window-theme = light"))
    }

    func testDarkTheme() {
        let l = lines(input(theme: .dark))
        XCTAssertTrue(l.contains("theme = Apple System Colors"))
        XCTAssertTrue(l.contains("window-theme = dark"))
    }

    func testOpacityFormattedToTwoDecimals() {
        XCTAssertTrue(lines(input(opacity: 0.6)).contains("background-opacity = 0.60"))
    }

    func testBlurRoundedToInt() {
        XCTAssertTrue(lines(input(blur: 20.4)).contains("background-blur = 20"))
        XCTAssertTrue(lines(input(blur: 23.6)).contains("background-blur = 24"))
    }

    func testCursorStylePassthrough() {
        XCTAssertTrue(lines(input(cursor: "bar")).contains("cursor-style = bar"))
    }

    func testFontSizeFormattedToOneDecimal() {
        XCTAssertTrue(lines(input(fontSize: 13)).contains("font-size = 13.0"))
    }

    func testFontFamilyOmittedWhenEmptyPresentWhenSet() {
        XCTAssertFalse(lines(input(fontFamily: "")).contains { $0.hasPrefix("font-family") })
        XCTAssertTrue(lines(input(fontFamily: "Menlo")).contains("font-family = Menlo"))
    }

    func testWorkingDirectoryDefaultsToHome() {
        XCTAssertTrue(lines(input(workingDirectory: "", home: "/Users/test")).contains("working-directory = /Users/test"))
        XCTAssertTrue(lines(input(workingDirectory: "/tmp/x", home: "/Users/test")).contains("working-directory = /tmp/x"))
    }

    func testShellCommandOmittedWhenEmptyPresentWhenSet() {
        XCTAssertFalse(lines(input(shell: "")).contains { $0.hasPrefix("command") })
        XCTAssertTrue(lines(input(shell: "/bin/zsh")).contains("command = /bin/zsh"))
    }
}
