import Foundation

/// How the terminal resolves light/dark.
public enum TerminalThemeMode: String {
    case system
    case light
    case dark
}

/// Everything the terminal-config renderer needs, as plain values — no
/// dependency on the app's settings object, so it's trivially testable.
public struct TerminalConfigInput {
    public var backgroundOpacity: Double
    public var blurAmount: Double
    public var cursorStyle: String
    public var fontSize: Double
    public var fontFamily: String
    public var theme: TerminalThemeMode
    /// Empty means "use the home directory".
    public var workingDirectory: String
    public var homeDirectory: String
    /// Empty means "use the login shell".
    public var shellPath: String

    public init(
        backgroundOpacity: Double,
        blurAmount: Double,
        cursorStyle: String,
        fontSize: Double,
        fontFamily: String,
        theme: TerminalThemeMode,
        workingDirectory: String,
        homeDirectory: String,
        shellPath: String
    ) {
        self.backgroundOpacity = backgroundOpacity
        self.blurAmount = blurAmount
        self.cursorStyle = cursorStyle
        self.fontSize = fontSize
        self.fontFamily = fontFamily
        self.theme = theme
        self.workingDirectory = workingDirectory
        self.homeDirectory = homeDirectory
        self.shellPath = shellPath
    }
}

/// Render the terminal engine's configuration file from the given input.
/// The engine stays stock; SideTerminal only feeds it this config.
public func renderTerminalConfig(_ input: TerminalConfigInput) -> String {
    var lines: [String] = [
        "# Generated by SideTerminal — edits are overwritten.",
        "macos-non-native-fullscreen = false",
        "confirm-close-surface = false",
        "window-padding-x = 14",
        "window-padding-y = 12",
        "window-padding-balance = true",
        "mouse-hide-while-typing = true",
        "shell-integration = detect",
        // Shell integration forces a bar cursor at the prompt, which would
        // silently override the Cursor Style setting.
        "shell-integration-features = no-cursor",
        "link-url = true",
    ]

    lines.append("background-opacity = \(String(format: "%.2f", input.backgroundOpacity))")
    lines.append("background-blur = \(Int(input.blurAmount.rounded()))")
    lines.append("cursor-style = \(input.cursorStyle)")
    lines.append("font-size = \(String(format: "%.1f", input.fontSize))")

    if !input.fontFamily.isEmpty {
        lines.append("font-family = \(input.fontFamily)")
    }

    // Apple System Colors keeps the palette native and premium in both
    // appearances; the engine resolves light/dark automatically.
    switch input.theme {
    case .system:
        lines.append("theme = light:Apple System Colors Light,dark:Apple System Colors")
        lines.append("window-theme = auto")
    case .light:
        lines.append("theme = Apple System Colors Light")
        lines.append("window-theme = light")
    case .dark:
        lines.append("theme = Apple System Colors")
        lines.append("window-theme = dark")
    }

    let cwd = input.workingDirectory.isEmpty ? input.homeDirectory : input.workingDirectory
    lines.append("working-directory = \(cwd)")

    if !input.shellPath.isEmpty {
        lines.append("command = \(input.shellPath)")
    }

    return lines.joined(separator: "\n") + "\n"
}
